### ISSUE TITLE
Cannot convert to pdf

### ISSUE THREAD

**Issue by sebelk** [gettalong/kramdown#340]
Hi, When I run:

`kramdown   posts/playgroud-kramdown.kd -o pdf > somefile.pdf`

it results in:

```
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- prawn (LoadError)
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/share/gems/gems/kramdown-1.11.1/lib/kramdown/converter/pdf.rb:10:in `<top (required)>'
        from /usr/local/share/gems/gems/kramdown-1.11.1/lib/kramdown/document.rb:119:in `const_defined?'
        from /usr/local/share/gems/gems/kramdown-1.11.1/lib/kramdown/document.rb:119:in `method_missing'
        from /usr/local/share/gems/gems/kramdown-1.11.1/bin/kramdown:61:in `block in <top (required)>'
        from /usr/local/share/gems/gems/kramdown-1.11.1/bin/kramdown:61:in `each'
        from /usr/local/share/gems/gems/kramdown-1.11.1/bin/kramdown:61:in `<top (required)>'
        from /usr/local/bin/kramdown:23:in `load'
        from /usr/local/bin/kramdown:23:in `<main>'
```

```
kramdown -v
1.11.1
```

What's wrong?

Thanks in advance!

**Comment by gettalong** [comment]
You need to install the prawn library that is required for converting to PDF.

**Comment by sebelk** [comment]
Hi Thomas, I've installed them:

```
rpm -q rubygem-pdf-core rubygem-prawn rubygem-kramdown
rubygem-pdf-core-0.5.1-1.fc23.noarch
rubygem-prawn-2.0.1-1.fc23.noarch
rubygem-kramdown-1.11.1-1.fc23.noarch
```

But the error is just the same as before :(

Am I doing something wrong with gem paths?

Thanks in advance

**Comment by sebelk** [comment]
Now it worked!

I've done: 
`gem install prawn-table`

Thanks!
