### ISSUE TITLE
What am I doing wrong with input: 'html'?

### ISSUE THREAD

**Issue by stephenbaidu** [gettalong/kramdown#371]
I have the code below and cannot generate a PDF

~~~ ruby
html = <<-eos
  <p markdown="1">
    <table class="my-table">
      <thead>
        <tr><th>Price</th><th>Quantity</th><th>Total</th></tr>
      </thead>
      <tbody>
        <tr><td>2</td><td>3</td><td>6</td></tr>
        <tr><td>4</td><td>2</td><td>8</td></tr>
        <tr><td>6</td><td>1</td><td>6</td></tr>
      </tbody>
    </table>
    This works without problems because it is parsed as
    span-level <b>elements</b>
  </p>
eos

file = File.open(Rails.root.join('db', 'fixtures', 'xyz.pdf'), 'wb+')
file.write(Kramdown::Document.new(html, input: 'html').to_pdf)
file.close
~~~

It currently returns the following error with stack trace
~~~ bash
TypeError: can't dup Float
	from /Users/stephen/.rvm/gems/ruby-2.1.2/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:359:in `dup'
	from /Users/stephen/.rvm/gems/ruby-2.1.2/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:359:in `collect'
	from /Users/stephen/.rvm/gems/ruby-2.1.2/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:359:in `original_text'
	from /Users/stephen/.rvm/gems/ruby-2.1.2/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:367:in `normalize_encoding'
	from /Users/stephen/.rvm/gems/ruby-2.1.2/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:351:in `normalized_text'
	from /Users/stephen/.rvm/gems/ruby-2.1.2/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:214:in `block (3 levels) in render'
	from /Users/stephen/.rvm/gems/ruby-2.1.2/gems/pdf-core-0.6.1/lib/pdf/core/text.rb:182:in `text_rendering_mode'
	from /Users/stephen/.rvm/gems/ruby-2.1.2/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:211:in `block (2 levels) in render'
	from /Users/stephen/.rvm/gems/ruby-2.1.2/gems/pdf-core-0.6.1/lib/pdf/core/text.rb:204:in `character_spacing'
	from /Users/stephen/.rvm/gems/ruby-2.1.2/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:210:in `block in render'
	from /Users/stephen/.rvm/gems/ruby-2.1.2/gems/prawn-2.1.0/lib/prawn/font.rb:207:in `save_font'
	from /Users/stephen/.rvm/gems/ruby-2.1.2/gems/prawn-2.1.0/lib/prawn/text/formatted/box.rb:209:in `render'
	from /Users/stephen/.rvm/gems/ruby-2.1.2/gems/prawn-2.1.0/lib/prawn/text.rb:376:in `fill_formatted_text_box'
	from /Users/stephen/.rvm/gems/ruby-2.1.2/gems/prawn-2.1.0/lib/prawn/text.rb:215:in `formatted_text'
	from /Users/stephen/.rvm/gems/ruby-2.1.2/gems/kramdown-1.11.1/lib/kramdown/converter/pdf.rb:594:in `block in render_padded_and_formatted_text'
	from /Users/stephen/.rvm/gems/ruby-2.1.2/gems/kramdown-1.11.1/lib/kramdown/converter/pdf.rb:587:in `with_block_padding'
... 3 levels...
	from /Users/stephen/.rvm/gems/ruby-2.1.2/gems/kramdown-1.11.1/lib/kramdown/converter/pdf.rb:79:in `convert'
	from /Users/stephen/.rvm/gems/ruby-2.1.2/gems/kramdown-1.11.1/lib/kramdown/converter/pdf.rb:93:in `block in inner'
	from /Users/stephen/.rvm/gems/ruby-2.1.2/gems/kramdown-1.11.1/lib/kramdown/converter/pdf.rb:90:in `map'
	from /Users/stephen/.rvm/gems/ruby-2.1.2/gems/kramdown-1.11.1/lib/kramdown/converter/pdf.rb:90:in `inner'
	from /Users/stephen/.rvm/gems/ruby-2.1.2/gems/kramdown-1.11.1/lib/kramdown/converter/pdf.rb:111:in `render_root'
	from /Users/stephen/.rvm/gems/ruby-2.1.2/gems/kramdown-1.11.1/lib/kramdown/converter/pdf.rb:79:in `convert'
	from /Users/stephen/.rvm/gems/ruby-2.1.2/gems/kramdown-1.11.1/lib/kramdown/converter/base.rb:105:in `convert'
	from /Users/stephen/.rvm/gems/ruby-2.1.2/gems/kramdown-1.11.1/lib/kramdown/document.rb:120:in `method_missing'
	from (irb):397
	from /Users/stephen/.rvm/gems/ruby-2.1.2@global/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
	from /Users/stephen/.rvm/gems/ruby-2.1.2@global/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
	from /Users/stephen/.rvm/gems/ruby-2.1.2@global/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/stephen/.rvm/gems/ruby-2.1.2@global/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/stephen/.rvm/gems/ruby-2.1.2@global/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:9:in `require'
~~~

**Comment by gettalong** [comment]
You can't have a table inside a paragraph. If you move the table outside of the paragraph, everything works fine, see [kd.pdf](https://github.com/gettalong/kramdown/files/464752/kd.pdf).

**Comment by stephenbaidu** [comment]
@gettalong Ah thanks. One other problem is nested tables like below

``` ruby
html = <<-eos
  <table class="my-table">
    <thead>
      <tr><th>Price</th><th>Quantity</th><th>Total</th></tr>
    </thead>
    <tbody>
      <tr><td>2</td><td>3</td><td>6</td></tr>
      <tr><td>4</td><td>2</td><td>8</td></tr>
      <tr>
        <td>6</td>
        <td></td>
        <td>
          <table class="my-table">
            <thead>
              <tr><th>Price</th><th>Quantity</th><th>Total</th></tr>
            </thead>
            <tbody>
              <tr><td>2</td><td>3</td><td>6</td></tr>
              <tr><td>4</td><td>2</td><td>8</td></tr>
              <tr><td>6</td><td>1</td><td>6</td></tr>
            </tbody>
          </table>
        </td>
      </tr>
    </tbody>
  </table>
eos

file = File.open(Rails.root.join('db', 'fixtures', 'xyz.pdf'), 'wb+')
file.write(Kramdown::Document.new(html, input: 'html').to_pdf)
file.close
```

This does not raise any errors but gives a blank pdf. Any help on this is highly appreciated?

**Comment by gettalong** [comment]
Yeah, that's alright because if you convert the HTML to kramdown and not to PDF you will find that the table uses plain HTML and not kramdown.

The reason for this is that kramdown doesn't support nested tables and has not AST elements to represent them. This means that the table is represented as an HTML element and that cannot be output by the PDF converter.

**Comment by stephenbaidu** [comment]
Alright, thanks again
