### ISSUE TITLE
Trouble running tests

### ISSUE THREAD

**Issue by agriffis** [gettalong/kramdown#376]
I'm having trouble running the tests:

```
$ rake
NO RELEASE NOTES/CHANGES FILE
/usr/share/gems/gems/psych-2.0.17/lib/psych.rb:227: warning: already initialized constant Psych::VERSION
/usr/share/ruby/psych.rb:227: warning: previous definition of VERSION was here
/usr/share/gems/gems/psych-2.0.17/lib/psych.rb:230: warning: already initialized constant Psych::LIBYAML_VERSION
/usr/share/ruby/psych.rb:230: warning: previous definition of LIBYAML_VERSION was here
Skipping latex compilation tests because latex executable is missing
/usr/share/ruby/psych/class_loader.rb:54:in `path2class': undefined class/module RougeHTMLFormatters (ArgumentError)
        from /usr/share/ruby/psych/class_loader.rb:54:in `resolve'
        from /usr/share/ruby/psych/class_loader.rb:46:in `find'
        from /usr/share/ruby/psych/class_loader.rb:28:in `load'
        from /usr/share/ruby/psych/visitors/to_ruby.rb:396:in `resolve_class'
        from /usr/share/ruby/psych/visitors/to_ruby.rb:88:in `deserialize'
        from /usr/share/ruby/psych/visitors/to_ruby.rb:123:in `visit_Psych_Nodes_Scalar'
        from /usr/share/ruby/psych/visitors/visitor.rb:16:in `visit'
        from /usr/share/ruby/psych/visitors/visitor.rb:6:in `accept'
        from /usr/share/ruby/psych/visitors/to_ruby.rb:32:in `accept'
        from /usr/share/ruby/psych/visitors/to_ruby.rb:338:in `block in revive_hash'
        from /usr/share/ruby/psych/visitors/to_ruby.rb:336:in `each'
        from /usr/share/ruby/psych/visitors/to_ruby.rb:336:in `each_slice'
        from /usr/share/ruby/psych/visitors/to_ruby.rb:336:in `revive_hash'
        from /usr/share/ruby/psych/visitors/to_ruby.rb:162:in `visit_Psych_Nodes_Mapping'
        from /usr/share/ruby/psych/visitors/visitor.rb:16:in `visit'
        from /usr/share/ruby/psych/visitors/visitor.rb:6:in `accept'
        from /usr/share/ruby/psych/visitors/to_ruby.rb:32:in `accept'
        from /usr/share/ruby/psych/visitors/to_ruby.rb:338:in `block in revive_hash'
        from /usr/share/ruby/psych/visitors/to_ruby.rb:336:in `each'
        from /usr/share/ruby/psych/visitors/to_ruby.rb:336:in `each_slice'
        from /usr/share/ruby/psych/visitors/to_ruby.rb:336:in `revive_hash'
        from /usr/share/ruby/psych/visitors/to_ruby.rb:162:in `visit_Psych_Nodes_Mapping'
        from /usr/share/ruby/psych/visitors/visitor.rb:16:in `visit'
        from /usr/share/ruby/psych/visitors/visitor.rb:6:in `accept'
        from /usr/share/ruby/psych/visitors/to_ruby.rb:32:in `accept'
        from /usr/share/ruby/psych/visitors/to_ruby.rb:311:in `visit_Psych_Nodes_Document'
        from /usr/share/ruby/psych/visitors/visitor.rb:16:in `visit'
        from /usr/share/ruby/psych/visitors/visitor.rb:6:in `accept'
        from /usr/share/ruby/psych/visitors/to_ruby.rb:32:in `accept'
        from /usr/share/ruby/psych/nodes/node.rb:38:in `to_ruby'
        from /usr/share/ruby/psych.rb:253:in `load'
        from /home/aron/src/kramdown/test/test_files.rb:364:in `block in <class:TestFiles>'
        from /home/aron/src/kramdown/test/test_files.rb:362:in `each'
        from /home/aron/src/kramdown/test/test_files.rb:362:in `<class:TestFiles>'
        from /home/aron/src/kramdown/test/test_files.rb:33:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/gems/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:15:in `block in <main>'
        from /usr/share/gems/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:4:in `select'
        from /usr/share/gems/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -I"lib:test" -I"/usr/share/gems/gems/rake-10.4.2/lib" "/usr/share/gems/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "test/test_files.rb" "test/test_location.rb" "test/test_string_scanner_kramdown.rb" ]

Tasks: TOP => default => test
(See full trace by running task with --trace)
```

This is a simple checkout of master. What am I missing?

**Comment by agriffis** [comment]
Hmm, this is part of the problem:

```
begin
  require 'kramdown/converter/syntax_highlighter/rouge'

  # custom formatter for tests
  class RougeHTMLFormatters < ::Rouge::Formatters::HTML
    tag 'rouge_html_formatters'

    def stream(tokens, &b)
      yield %(<div class="custom-class">)
      super
      yield %(</div>)
    end
  end
rescue LoadError, SyntaxError, NameError
end
```

The `rescue` is hiding the error that prevents `RougeHTMLFormatters` from being defined, and Psych can't deserialize without it. Removing the `rescue` yields this error:

```
 rake
NO RELEASE NOTES/CHANGES FILE
/usr/share/gems/gems/psych-2.0.17/lib/psych.rb:227: warning: already initialized constant Psych::VERSION
/usr/share/ruby/psych.rb:227: warning: previous definition of VERSION was here
/usr/share/gems/gems/psych-2.0.17/lib/psych.rb:230: warning: already initialized constant Psych::LIBYAML_VERSION
/usr/share/ruby/psych.rb:230: warning: previous definition of LIBYAML_VERSION was here
/home/aron/src/kramdown/test/test_files.rb:19:in `<top (required)>': uninitialized constant Rouge (NameError)
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/gems/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:15:in `block in <main>'
        from /usr/share/gems/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:4:in `select'
        from /usr/share/gems/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -I"lib:test" -I"/usr/share/gems/gems/rake-10.4.2/lib" "/usr/share/gems/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "test/test_files.rb" "test/test_location.rb" "test/test_string_scanner_kramdown.rb" ]

Tasks: TOP => default => test
(See full trace by running task with --trace)
```

and kramdown's `rouge.rb` hides its loading error here:

```
    begin
      require 'rouge'

      # Highlighting via Rouge is available if this constant is +true+.
      AVAILABLE = true
    rescue LoadError, SyntaxError
      AVAILABLE = false  # :nodoc:
    end
```

so it seems that the tests depend on rouge, but I don't presently have it installed...

**Comment by agriffis** [comment]
Installing rouge fixed it. Lots of tests still failing, but not because of this problem at least :-)

```
dnf install rubygem-rouge
```
