### ISSUE TITLE
GFM header IDs fail if header contains span markup

### ISSUE THREAD

**Issue by nfagerlund** [gettalong/kramdown#391]
On GitHub proper (and kramdown prior to 1.13.0), the following MD:

```
### `code-span`
```

...results in the following HTML:

```
<h3 id="code-span"><code>code-span</code></h3>
```

Now, though, it results in something like:

```
<h3 id="-18"><code>code-span</code></h3>
```

(...assuming this wasn't the first code-span header in the page.)

This is bad, and also does not match what GitHub does.

**Comment by gettalong** [comment]
Thanks for the additional test case, I will release a bug fix release soon that fixes this.

**Comment by gettalong** [comment]
In addition the bug fix release will fix problems with entities, smart quotes and other specially parsed kramdown elements.

**Comment by parkr** [comment]
Just upgraded to v1.13.2 and noticing some errors like:

```text
---> Can't handle generic non-integer character reference 'raquo_space'
.bundle/ruby/2.3.0/gems/kramdown-1.13.2/lib/kramdown/utils/entities.rb:323:in `block in <module:Entities>'
.bundle/ruby/2.3.0/gems/kramdown-1.13.2/lib/kramdown/utils/entities.rb:337:in `entity'
.bundle/ruby/2.3.0/gems/kramdown-1.13.2/lib/kramdown/parser/gfm.rb:87:in `block in update_raw_text'
.bundle/ruby/2.3.0/gems/kramdown-1.13.2/lib/kramdown/parser/gfm.rb:89:in `block (2 levels) in update_raw_text'
.bundle/ruby/2.3.0/gems/kramdown-1.13.2/lib/kramdown/parser/gfm.rb:89:in `each'
.bundle/ruby/2.3.0/gems/kramdown-1.13.2/lib/kramdown/parser/gfm.rb:89:in `block in update_raw_text'
.bundle/ruby/2.3.0/gems/kramdown-1.13.2/lib/kramdown/parser/gfm.rb:93:in `update_raw_text'
.bundle/ruby/2.3.0/gems/kramdown-1.13.2/lib/kramdown/parser/kramdown.rb:189:in `block in update_tree'
.bundle/ruby/2.3.0/gems/kramdown-1.13.2/lib/kramdown/parser/kramdown.rb:164:in `map!'
.bundle/ruby/2.3.0/gems/kramdown-1.13.2/lib/kramdown/parser/kramdown.rb:164:in `update_tree'
.bundle/ruby/2.3.0/gems/kramdown-1.13.2/lib/kramdown/parser/kramdown.rb:90:in `parse'
.bundle/ruby/2.3.0/gems/kramdown-1.13.2/lib/kramdown/parser/gfm.rb:44:in `parse'
.bundle/ruby/2.3.0/gems/kramdown-1.13.2/lib/kramdown/parser/base.rb:69:in `parse'
.bundle/ruby/2.3.0/gems/kramdown-1.13.2/lib/kramdown/document.rb:107:in `initialize'
.bundle/ruby/2.3.0/gems/jekyll-3.3.1/lib/jekyll/converters/markdown/kramdown_parser.rb:41:in `new'
...
```

Could we consider a fallback mechanism for this PR so it doesn't break on headings when it gets confused on the entity?

**Comment by gettalong** [comment]
@parks Thanks, this is a bug in handling typographic symbols for GFM header IDs - will fix that for the next release.

**Comment by gettalong** [comment]
The special typographic syms laquo_space and raquo_space are now handled correctly - will be in the next release.
