### ISSUE TITLE
NoMethodError: undefined method `<<' for nil:NilClass in parse paragraph

### ISSUE THREAD

**Issue by eddibravo** [gettalong/kramdown#466]
My english is not very good, so only logs without words.

``` bush
$ bundle show | grep kramdown
  * kramdown (1.15.0)
```
``` bush
2.3.3 :001 > Kramdown::Document.new('<p><img src="http://example.com/image.png"></p> some text', :html_to_native => true).to_kramdown
NoMethodError: undefined method `<<' for nil:NilClass
from /home/bravo/.rvm/gems/ruby-2.3.3@project_name/gems/kramdown-1.15.0/lib/kramdown/parser/kramdown/paragraph.rb:39:in `parse_paragraph'
from /home/bravo/.rvm/gems/ruby-2.3.3@project_name/gems/kramdown-1.15.0/lib/kramdown/parser/kramdown.rb:148:in `block (2 levels) in parse_blocks'
from /home/bravo/.rvm/gems/ruby-2.3.3@project_name/gems/kramdown-1.15.0/lib/kramdown/parser/kramdown.rb:146:in `any?'
from /home/bravo/.rvm/gems/ruby-2.3.3@project_name/gems/kramdown-1.15.0/lib/kramdown/parser/kramdown.rb:146:in `block in parse_blocks'
from /home/bravo/.rvm/gems/ruby-2.3.3@project_name/gems/kramdown-1.15.0/lib/kramdown/parser/kramdown.rb:144:in `catch'
from /home/bravo/.rvm/gems/ruby-2.3.3@project_name/gems/kramdown-1.15.0/lib/kramdown/parser/kramdown.rb:144:in `parse_blocks'
from /home/bravo/.rvm/gems/ruby-2.3.3@project_name/gems/kramdown-1.15.0/lib/kramdown/parser/kramdown.rb:89:in `parse'
from /home/bravo/.rvm/gems/ruby-2.3.3@project_name/gems/kramdown-1.15.0/lib/kramdown/parser/base.rb:69:in `parse'
from /home/bravo/.rvm/gems/ruby-2.3.3@project_name/gems/kramdown-1.15.0/lib/kramdown/document.rb:104:in `initialize'
```

**Comment by gettalong** [comment]
Thanks for reporting this bug - will be fixed with next release!

**Comment by gettalong** [comment]
I have found the problem and fixed it.
