### ISSUE TITLE
Error with PDF generation

### ISSUE THREAD

**Issue by gonsie** [gettalong/kramdown#480]
When I try to generate a PDF through the command line tool I get an error: 

~~~sh
$ echo -e "# header\n\nsome para\n\n* a list\n* item\n" | kramdown -o pdf > /tmp/o.pdf
/Users/gonsiorowski1/Projects/homebrew/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- prawn (LoadError)
	from /Users/gonsiorowski1/Projects/homebrew/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/gonsiorowski1/Projects/homebrew/lib/ruby/gems/2.4.0/gems/kramdown-1.16.2/lib/kramdown/converter/pdf.rb:10:in `<top (required)>'
	from /Users/gonsiorowski1/Projects/homebrew/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/gonsiorowski1/Projects/homebrew/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/gonsiorowski1/Projects/homebrew/lib/ruby/gems/2.4.0/gems/kramdown-1.16.2/lib/kramdown/document.rb:116:in `const_defined?'
	from /Users/gonsiorowski1/Projects/homebrew/lib/ruby/gems/2.4.0/gems/kramdown-1.16.2/lib/kramdown/document.rb:116:in `method_missing'
	from /Users/gonsiorowski1/Projects/homebrew/lib/ruby/gems/2.4.0/gems/kramdown-1.16.2/bin/kramdown:84:in `block in <top (required)>'
	from /Users/gonsiorowski1/Projects/homebrew/lib/ruby/gems/2.4.0/gems/kramdown-1.16.2/bin/kramdown:84:in `each'
	from /Users/gonsiorowski1/Projects/homebrew/lib/ruby/gems/2.4.0/gems/kramdown-1.16.2/bin/kramdown:84:in `<top (required)>'
	from /Users/gonsiorowski1/Projects/homebrew/bin/kramdown:23:in `load'
	from /Users/gonsiorowski1/Projects/homebrew/bin/kramdown:23:in `<main>'
~~~

I am on a Mac (using homebrew) to run:
- `ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin15]`
- Kramdown version `1.16.2`

**Comment by gettalong** [comment]
Since the direct PDF output needs Prawn as dependency, you need to install it first. Doing a `gem install prawn prawn-table` should do the trick.
