### ISSUE TITLE
After 2.0.0 came out, MD to PDF conversion doesn't work anymore.

### ISSUE THREAD

**Issue by andrea-ligios** [gettalong/kramdown#570]
Hello, 
I'm the author of [WIKI2PDF](https://gitlab.com/Andrea.Ligios/Wiki2PDF), a script which turns GitLab Wiki pages from MarkDown and AsciiDoc into PDF.

It's worked great until yesterday, when 2.0.0 came out. 

Now I get the following result:

![immagine](https://user-images.githubusercontent.com/11974750/51484789-bdec6280-1d9c-11e9-9dab-6ff8f2188d26.png)

The command I run is this:

```bash
find . -name '*.md' -exec sh -c 'echo "Processing $0" \ 
  && kramdown $0 --output pdf > "${0%.*}".pdf \
  && echo "Done.\n"' {} \;
```

The errors I get are these:

```
> Processing ./second-md-page.md
> /var/lib/gems/2.5.0/gems/kramdown-2.0.0/lib/kramdown/document.rb:120:in `method_missing': undefined method `to_pdf' for #<Kramdown::Document:0x000055bd6b9b1580> (NoMethodError)
> 	from /var/lib/gems/2.5.0/gems/kramdown-2.0.0/bin/kramdown:97:in `block in <top (required)>'
> 	from /var/lib/gems/2.5.0/gems/kramdown-2.0.0/bin/kramdown:97:in `each'
> 	from /var/lib/gems/2.5.0/gems/kramdown-2.0.0/bin/kramdown:97:in `<top (required)>'
> 	from /usr/local/bin/kramdown:23:in `load'
> 	from /usr/local/bin/kramdown:23:in `<main>'
> Processing ./another@sub@folder@inner-markdown.md
> /var/lib/gems/2.5.0/gems/kramdown-2.0.0/lib/kramdown/document.rb:120:in `method_missing': undefined method `to_pdf' for #<Kramdown::Document:0x00005642fc351340> (NoMethodError)
> 	from /var/lib/gems/2.5.0/gems/kramdown-2.0.0/bin/kramdown:97:in `block in <top (required)>'
> 	from /var/lib/gems/2.5.0/gems/kramdown-2.0.0/bin/kramdown:97:in `each'
> 	from /var/lib/gems/2.5.0/gems/kramdown-2.0.0/bin/kramdown:97:in `<top (required)>'
> 	from /usr/local/bin/kramdown:23:in `load'
> 	from /usr/local/bin/kramdown:23:in `<main>'
> Processing ./Sample-MarkDown-Wiki-Page.md
> /var/lib/gems/2.5.0/gems/kramdown-2.0.0/lib/kramdown/document.rb:120:in `method_missing': undefined method `to_pdf' for #<Kramdown::Document:0x000055a378114790> (NoMethodError)
> 	from /var/lib/gems/2.5.0/gems/kramdown-2.0.0/bin/kramdown:97:in `block in <top (required)>'
> 	from /var/lib/gems/2.5.0/gems/kramdown-2.0.0/bin/kramdown:97:in `each'
> 	from /var/lib/gems/2.5.0/gems/kramdown-2.0.0/bin/kramdown:97:in `<top (required)>'
> 	from /usr/local/bin/kramdown:23:in `load'
> 	from /usr/local/bin/kramdown:23:in `<main>'
```

Any chance of adapting the command and have it working again? Or should I rely on a previous version for now?

Thanks in advance,
Cheers

**Comment by arthurattwell** [comment]
Perhaps this is because the PDF converter is now a separate gem? https://github.com/kramdown/converter-pdf

**Comment by gettalong** [comment]
Yes, that is the reason. Installing the gem will allow the kramdown binary to use the `-o pdf` option.
