### ISSUE TITLE
How to specify Rouge formatter from YAML config file

### ISSUE THREAD

**Issue by ZacBlanco** [gettalong/kramdown#581]
Hi there. I'm working on a Jekyll-based site using Kramdown and rouge. I don't really have much knowledge of Ruby so I'm having a tough time figuring out how to fix this. 

There is [an option we can specify on the `rouge` highlighter under `syntax_highlighter_opts => formatter`](https://kramdown.gettalong.org/syntax_highlighter/rouge.html). I want to attempt to use the non-standard formatter for rouge `HTMLLinewise` but when I set my jekyll `_config.yml` to

```
markdown: kramdown
kramdown:
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    formatter: HTMLLinewise
```

I get an error with Jekyll

```
undefined method `new' for "HTMLLinewise":String Did you mean? next
```

I can't seem to figure out the proper value to put for the formatter. It looks like Ruby is interpreting the formatter as a string when it should be creating an instance of the formatter? It's hard for me to tell.

Edit: Here's a stacktrace from jekyll

```
Traceback (most recent call last):
	39: from /home/zac/gems/bin/jekyll:23:in `<main>'
	38: from /home/zac/gems/bin/jekyll:23:in `load'
	37: from /home/zac/gems/gems/jekyll-3.8.5/exe/jekyll:15:in `<top (required)>'
	36: from /usr/lib/ruby/vendor_ruby/mercenary.rb:19:in `program'
	35: from /usr/lib/ruby/vendor_ruby/mercenary/program.rb:42:in `go'
	34: from /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `execute'
	33: from /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `each'
	32: from /usr/lib/ruby/vendor_ruby/mercenary/command.rb:220:in `block in execute'
	31: from /home/zac/gems/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
	30: from /home/zac/gems/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:93:in `start'
	29: from /home/zac/gems/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:93:in `each'
	28: from /home/zac/gems/gems/jekyll-3.8.5/lib/jekyll/commands/serve.rb:93:in `block in start'
	27: from /home/zac/gems/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:36:in `process'
	26: from /home/zac/gems/gems/jekyll-3.8.5/lib/jekyll/commands/build.rb:65:in `build'
	25: from /home/zac/gems/gems/jekyll-3.8.5/lib/jekyll/command.rb:28:in `process_site'
	24: from /home/zac/gems/gems/jekyll-3.8.5/lib/jekyll/site.rb:71:in `process'
	23: from /home/zac/gems/gems/jekyll-3.8.5/lib/jekyll/site.rb:192:in `render'
	22: from /home/zac/gems/gems/jekyll-3.8.5/lib/jekyll/site.rb:471:in `render_pages'
	21: from /home/zac/gems/gems/jekyll-3.8.5/lib/jekyll/site.rb:471:in `each'
	20: from /home/zac/gems/gems/jekyll-3.8.5/lib/jekyll/site.rb:472:in `block in render_pages'
	19: from /home/zac/gems/gems/jekyll-3.8.5/lib/jekyll/site.rb:479:in `render_regenerated'
	18: from /home/zac/gems/gems/jekyll-3.8.5/lib/jekyll/renderer.rb:62:in `run'
	17: from /home/zac/gems/gems/jekyll-3.8.5/lib/jekyll/renderer.rb:83:in `render_document'
	16: from /home/zac/gems/gems/jekyll-3.8.5/lib/jekyll/renderer.rb:99:in `convert'
	15: from /home/zac/gems/gems/jekyll-3.8.5/lib/jekyll/renderer.rb:99:in `reduce'
	14: from /home/zac/gems/gems/jekyll-3.8.5/lib/jekyll/renderer.rb:99:in `each'
	13: from /home/zac/gems/gems/jekyll-3.8.5/lib/jekyll/renderer.rb:101:in `block in convert'
	12: from /home/zac/gems/gems/jekyll-3.8.5/lib/jekyll/converters/markdown.rb:77:in `convert'
	11: from /home/zac/gems/gems/jekyll-3.8.5/lib/jekyll/converters/markdown/kramdown_parser.rb:40:in `convert'
	10: from /usr/lib/ruby/vendor_ruby/kramdown/document.rb:117:in `method_missing'
	 9: from /usr/lib/ruby/vendor_ruby/kramdown/converter/base.rb:105:in `convert'
	 8: from /usr/lib/ruby/vendor_ruby/kramdown/converter/html.rb:57:in `convert'
	 7: from /usr/lib/ruby/vendor_ruby/kramdown/converter/html.rb:337:in `convert_root'
	 6: from /usr/lib/ruby/vendor_ruby/kramdown/converter/html.rb:69:in `inner'
	 5: from /usr/lib/ruby/vendor_ruby/kramdown/converter/html.rb:69:in `each'
	 4: from /usr/lib/ruby/vendor_ruby/kramdown/converter/html.rb:70:in `block in inner'
	 3: from /usr/lib/ruby/vendor_ruby/kramdown/converter/html.rb:96:in `convert_codeblock'
	 2: from /usr/lib/ruby/vendor_ruby/kramdown/converter/base.rb:207:in `highlight_code'
	 1: from /usr/lib/ruby/vendor_ruby/kramdown/converter.rb:47:in `block (2 levels) in <module:Converter>'
/usr/lib/ruby/vendor_ruby/kramdown/converter/syntax_highlighter/rouge.rb:38:in `call': undefined method `new' for "HTMLLinewise":String (NoMethodError)

```

**Comment by ZacBlanco** [comment]
So I figured out that updating to a later version of kramdown fixed my issue. I noticed from the paths of the stack I'm using system libraries as opposed to my installed jekyll which is using my user-directory based gems.

However it looks like not all of the parsers have been properly implemented by Rouge.

**Comment by gettalong** [comment]
Please try kramdown together with Rouge without Jekyll, for example by using the `kramdown` binary. If the error still exists, it is a kramdown issue. Otherwise it is most probably a Jekyll issue.

**Comment by gettalong** [comment]
@ZacBlanco I think you fixed the issue yourself? Will close it but feel free to comment if necessary.
