### ISSUE TITLE
Handle ambiguous language code blocks (Rouge)

### ISSUE THREAD

**Issue by parkr** [gettalong/kramdown#630]
Hey! This is a bug we found on GitHub Pages. Kramdown 1.17.0 and Rouge 3.11.0. I didn't find anything in this issue tracker about this error so I'm filing one here.

### Problem statement

When a user has a code block without specifying the language, Rouge tries to guess what language it is and highlight accordingly. When it gets too many options, it raises a `Rouge::Guesser::Ambiguous` error.

Here's an example that breaks kramdown:

```text
---
layout: post
---

## **Header**

This is a paragraph.

    <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN">

    <html>

    <head>

    </head>

    <body>

    </body>

    </html>

This is a paragraph.
```

In this example, the code block is created by indenting. If you put this into a `post` in your site, it will raise an error:

```console
$ cat _posts/2019-10-11-broken-highlight.md | bundle exec kramdown --syntax-highlighter rouge
bundler: failed to load command: kramdown (/Users/parkr/.rbenv/versions/2.6.5/bin/kramdown)
Rouge::Guesser::Ambiguous: Ambiguous guess: can't decide between ["html", "mason", "xml"]
  /Users/parkr/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rouge-3.11.0/lib/rouge/lexer.rb:178:in `guess'
  /Users/parkr/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rouge-3.11.0/lib/rouge/lexer.rb:79:in `find_fancy'
  /Users/parkr/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/kramdown-1.17.0/lib/kramdown/converter/syntax_highlighter/rouge.rb:27:in `call'
  /Users/parkr/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/kramdown-1.17.0/lib/kramdown/converter.rb:47:in `block (2 levels) in <module:Converter>'
  /Users/parkr/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/kramdown-1.17.0/lib/kramdown/converter/base.rb:207:in `highlight_code'
  /Users/parkr/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/kramdown-1.17.0/lib/kramdown/converter/html.rb:96:in `convert_codeblock'
  /Users/parkr/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/kramdown-1.17.0/lib/kramdown/converter/html.rb:70:in `block in inner'
  /Users/parkr/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/kramdown-1.17.0/lib/kramdown/converter/html.rb:69:in `each'
  /Users/parkr/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/kramdown-1.17.0/lib/kramdown/converter/html.rb:69:in `inner'
  /Users/parkr/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/kramdown-1.17.0/lib/kramdown/converter/html.rb:341:in `convert_root'
  /Users/parkr/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/kramdown-1.17.0/lib/kramdown/converter/html.rb:57:in `convert'
  /Users/parkr/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/kramdown-1.17.0/lib/kramdown/converter/base.rb:105:in `convert'
  /Users/parkr/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/kramdown-1.17.0/lib/kramdown/document.rb:117:in `method_missing'
  /Users/parkr/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/kramdown-1.17.0/bin/kramdown:98:in `block in <top (required)>'
  /Users/parkr/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/kramdown-1.17.0/bin/kramdown:98:in `each'
  /Users/parkr/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/kramdown-1.17.0/bin/kramdown:98:in `<top (required)>'
  /Users/parkr/.rbenv/versions/2.6.5/bin/kramdown:23:in `load'
  /Users/parkr/.rbenv/versions/2.6.5/bin/kramdown:23:in `<top (required)>'
```

I think raising an error is not ideal for the user.

### Possible Solutions

1. One attractive solution is to simply pick the first option and force that syntax. In this case for example, the first option is `html`, which would have accurately highlighted the text. You can imagine, however, that at times the first guess would be an improper fit.
2. An alternative failsafe solution is to simply highlight it as `text`. It would still show up as a code block, but wouldn't have any highlighting. Since the user didn't specify a language, I think this would be an acceptable solution.

What do you think?

/cc the Jekyll issue I opened about this: https://github.com/jekyll/jekyll/issues/7858

**Comment by gettalong** [comment]
Please confirm that this is also a problem with the latest versions of kramdown and rouge! Trying with kramdown 2.1.0 and rouge 3.11.1 works without a problem and gives the following result:

~~~ HTML
<h2 id="header"><strong>Header</strong></h2>

<p>This is a paragraph.</p>

<pre><code>&lt;!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN"&gt;

&lt;html&gt;

&lt;head&gt;

&lt;/head&gt;

&lt;body&gt;

&lt;/body&gt;

&lt;/html&gt;
</code></pre>

<p>This is a paragraph.</p>
~~~

**Comment by parkr** [comment]
I'm very sorry for not checking the latest versions! That's my bad.

We will proceed with the fixes in Jekyll and in GitHub Pages. Thank you!
